from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserErfolg(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, eid=None, status=None):  # noqa: E501
        """UserErfolg - a model defined in OpenAPI

        :param uid: The uid of this UserErfolg.  # noqa: E501
        :type uid: int
        :param eid: The eid of this UserErfolg.  # noqa: E501
        :type eid: int
        :param status: The status of this UserErfolg.  # noqa: E501
        :type status: bool
        """
        self.openapi_types = {
            'uid': int,
            'eid': int,
            'status': bool
        }

        self.attribute_map = {
            'uid': 'UID',
            'eid': 'EID',
            'status': 'Status'
        }

        self._uid = uid
        self._eid = eid
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'UserErfolg':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserErfolg of this UserErfolg.  # noqa: E501
        :rtype: UserErfolg
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> int:
        """Gets the uid of this UserErfolg.


        :return: The uid of this UserErfolg.
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid: int):
        """Sets the uid of this UserErfolg.


        :param uid: The uid of this UserErfolg.
        :type uid: int
        """

        self._uid = uid

    @property
    def eid(self) -> int:
        """Gets the eid of this UserErfolg.


        :return: The eid of this UserErfolg.
        :rtype: int
        """
        return self._eid

    @eid.setter
    def eid(self, eid: int):
        """Sets the eid of this UserErfolg.


        :param eid: The eid of this UserErfolg.
        :type eid: int
        """

        self._eid = eid

    @property
    def status(self) -> bool:
        """Gets the status of this UserErfolg.


        :return: The status of this UserErfolg.
        :rtype: bool
        """
        return self._status

    @status.setter
    def status(self, status: bool):
        """Sets the status of this UserErfolg.


        :param status: The status of this UserErfolg.
        :type status: bool
        """

        self._status = status
