from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, benutzername=None, passwort=None, profilbild=None, kmgelaufen=None, hoehenmeter=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param benutzername: The benutzername of this User.  # noqa: E501
        :type benutzername: str
        :param passwort: The passwort of this User.  # noqa: E501
        :type passwort: str
        :param profilbild: The profilbild of this User.  # noqa: E501
        :type profilbild: str
        :param kmgelaufen: The kmgelaufen of this User.  # noqa: E501
        :type kmgelaufen: float
        :param hoehenmeter: The hoehenmeter of this User.  # noqa: E501
        :type hoehenmeter: float
        """
        self.openapi_types = {
            'id': int,
            'benutzername': str,
            'passwort': str,
            'profilbild': str,
            'kmgelaufen': float,
            'hoehenmeter': float
        }

        self.attribute_map = {
            'id': 'ID',
            'benutzername': 'Benutzername',
            'passwort': 'Passwort',
            'profilbild': 'Profilbild',
            'kmgelaufen': 'kmgelaufen',
            'hoehenmeter': 'hoehenmeter'
        }

        self._id = id
        self._benutzername = benutzername
        self._passwort = passwort
        self._profilbild = profilbild
        self._kmgelaufen = kmgelaufen
        self._hoehenmeter = hoehenmeter

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def benutzername(self) -> str:
        """Gets the benutzername of this User.


        :return: The benutzername of this User.
        :rtype: str
        """
        return self._benutzername

    @benutzername.setter
    def benutzername(self, benutzername: str):
        """Sets the benutzername of this User.


        :param benutzername: The benutzername of this User.
        :type benutzername: str
        """

        self._benutzername = benutzername

    @property
    def passwort(self) -> str:
        """Gets the passwort of this User.


        :return: The passwort of this User.
        :rtype: str
        """
        return self._passwort

    @passwort.setter
    def passwort(self, passwort: str):
        """Sets the passwort of this User.


        :param passwort: The passwort of this User.
        :type passwort: str
        """

        self._passwort = passwort

    @property
    def profilbild(self) -> str:
        """Gets the profilbild of this User.


        :return: The profilbild of this User.
        :rtype: str
        """
        return self._profilbild

    @profilbild.setter
    def profilbild(self, profilbild: str):
        """Sets the profilbild of this User.


        :param profilbild: The profilbild of this User.
        :type profilbild: str
        """

        self._profilbild = profilbild

    @property
    def kmgelaufen(self) -> float:
        """Gets the kmgelaufen of this User.


        :return: The kmgelaufen of this User.
        :rtype: float
        """
        return self._kmgelaufen

    @kmgelaufen.setter
    def kmgelaufen(self, kmgelaufen: float):
        """Sets the kmgelaufen of this User.


        :param kmgelaufen: The kmgelaufen of this User.
        :type kmgelaufen: float
        """

        self._kmgelaufen = kmgelaufen

    @property
    def hoehenmeter(self) -> float:
        """Gets the hoehenmeter of this User.


        :return: The hoehenmeter of this User.
        :rtype: float
        """
        return self._hoehenmeter

    @hoehenmeter.setter
    def hoehenmeter(self, hoehenmeter: float):
        """Sets the hoehenmeter of this User.


        :param hoehenmeter: The hoehenmeter of this User.
        :type hoehenmeter: float
        """

        self._hoehenmeter = hoehenmeter
