from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ZielKoordinaten(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lng=None):  # noqa: E501
        """ZielKoordinaten - a model defined in OpenAPI

        :param lat: The lat of this ZielKoordinaten.  # noqa: E501
        :type lat: float
        :param lng: The lng of this ZielKoordinaten.  # noqa: E501
        :type lng: float
        """
        self.openapi_types = {
            'lat': float,
            'lng': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lng': 'lng'
        }

        self._lat = lat
        self._lng = lng

    @classmethod
    def from_dict(cls, dikt) -> 'ZielKoordinaten':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ziel_Koordinaten of this ZielKoordinaten.  # noqa: E501
        :rtype: ZielKoordinaten
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this ZielKoordinaten.


        :return: The lat of this ZielKoordinaten.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this ZielKoordinaten.


        :param lat: The lat of this ZielKoordinaten.
        :type lat: float
        """

        self._lat = lat

    @property
    def lng(self) -> float:
        """Gets the lng of this ZielKoordinaten.


        :return: The lng of this ZielKoordinaten.
        :rtype: float
        """
        return self._lng

    @lng.setter
    def lng(self, lng: float):
        """Sets the lng of this ZielKoordinaten.


        :param lng: The lng of this ZielKoordinaten.
        :type lng: float
        """

        self._lng = lng
