from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ZielErreicht(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, zid=None, datum=None):  # noqa: E501
        """ZielErreicht - a model defined in OpenAPI

        :param uid: The uid of this ZielErreicht.  # noqa: E501
        :type uid: int
        :param zid: The zid of this ZielErreicht.  # noqa: E501
        :type zid: int
        :param datum: The datum of this ZielErreicht.  # noqa: E501
        :type datum: date
        """
        self.openapi_types = {
            'uid': int,
            'zid': int,
            'datum': date
        }

        self.attribute_map = {
            'uid': 'UID',
            'zid': 'ZID',
            'datum': 'Datum'
        }

        self._uid = uid
        self._zid = zid
        self._datum = datum

    @classmethod
    def from_dict(cls, dikt) -> 'ZielErreicht':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ZielErreicht of this ZielErreicht.  # noqa: E501
        :rtype: ZielErreicht
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> int:
        """Gets the uid of this ZielErreicht.


        :return: The uid of this ZielErreicht.
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid: int):
        """Sets the uid of this ZielErreicht.


        :param uid: The uid of this ZielErreicht.
        :type uid: int
        """

        self._uid = uid

    @property
    def zid(self) -> int:
        """Gets the zid of this ZielErreicht.


        :return: The zid of this ZielErreicht.
        :rtype: int
        """
        return self._zid

    @zid.setter
    def zid(self, zid: int):
        """Sets the zid of this ZielErreicht.


        :param zid: The zid of this ZielErreicht.
        :type zid: int
        """

        self._zid = zid

    @property
    def datum(self) -> date:
        """Gets the datum of this ZielErreicht.


        :return: The datum of this ZielErreicht.
        :rtype: date
        """
        return self._datum

    @datum.setter
    def datum(self, datum: date):
        """Sets the datum of this ZielErreicht.


        :param datum: The datum of this ZielErreicht.
        :type datum: date
        """

        self._datum = datum
